### ISSUE TITLE
BoundaryEventHeadlessTaskService.java - cannot find symbol variable drawable

### ISSUE THREAD

**Issue by Eduard-Fernandez-HR** [skedlife/react-native-boundary#2]
Hey, @skedlife!

I am seeing the following error when I tried to run the library with an updated react-native version (0.75.2):

![Screenshot 2024-09-04 at 10 09 56 AM](https://github.com/user-attachments/assets/b2120003-7872-4409-a5dc-405283fa7cf7)

I'm upgrading from RN 0.64 where this package was working before, trying to get to the latest version of react native and on android i run into this issue witch prevents the android build from working 

Do you have any idea what I can do to fix it?

Thank you so much!

Platform
Android

Environment:
package	| version
react-native	0.75.2
react-native-boundary-sked	1.1.6
node	18.16.1
npm or yarn	npm v10.7.0

**Comment by NuclearKev** [comment]
Hi @Eduard-Fernandez-HR, we are currently using RN 0.73.7. I will attempt an upgrade and see if I get the same error message.

**Comment by Eduard-Fernandez-HR** [comment]
Thanks For taking a look at this @NuclearKev, I also tried a fresh react native project using `npx react-native init` and got the same error, not sure if it's my local config or if i should back track to the version your using, appreciate the help!

**Comment by NuclearKev** [comment]
Sorry for the delay in testing this, I am unable to find time right now to attempt this. If you can, try removing that line and seeing it works after that. All it does is set the icon for the notification.

**Comment by NuclearKev** [comment]
@Eduard-Fernandez-HR I've been able to reproduce this, however, I'm not sure what the solution is yet. I recommend that you just remove the two lines of code that refer to the R class for now.

**Comment by Eduard-Fernandez-HR** [comment]
@NuclearKev yeah my solution to get past this was to comment out those lines that use the R variable and then npm patch package

Example of Patch file in case anyone else comes across this issue:
[react-native-boundary-sked+1.1.6.patch](https://github.com/user-attachments/files/16980413/react-native-boundary-sked%2B1.1.6.patch)

**Comment by Eduard-Fernandez-HR** [comment]
Though i will note i'm still getting this issue on Android when i try to run Boundary.removeAll
![Screenshot 2024-09-12 at 9 58 06 AM](https://github.com/user-attachments/assets/76c37d34-74c6-46d9-979e-4a447ea88b36)
Still not sure how to fix this @NuclearKev if you have any ideas i would appreciate it, if i find a solution i'll post here

**Comment by NuclearKev** [comment]
@Eduard-Fernandez-HR Hmm, I'm not getting that error. Then again, I was unable to upgrade to RN 0.75.2. There seems to be some issue with metro when I attempt to upgrade. It's possible that things may have changed in the newer version that break the library.  If you're able to find a solution, please let me know and I can patch it.
